name: CI - Build and Push to Docker Hub

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: myapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------- Checkout Code ----------
      - name: Checkout Code
        uses: actions/checkout@v4

      # ---------- Login to Docker Hub ----------
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- Build Docker Image ----------
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      # ---------- Push Docker Image ----------
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
